### ISSUE TITLE
Settings > (Signatures|Quick Replies) > Text Not visible

### ISSUE THREAD

**Issue by davidsneighbour** [varlesh/Nylas-Arc-Dark-Theme#3]
In both settings panels are textareas with white background and white text.
Also the search fields in Encryption and Plugins are with white background (could be dark gray?).

![2016-06-21-2-jun](https://cloud.githubusercontent.com/assets/83281/16218159/9ee2c978-37a4-11e6-9881-ea823594c940.png)

**Comment by varlesh** [comment]
@pkollitsch Please reinstall fresh git-version. All fixed
